name: Documentation

on:
  push:
    branches:
      - 'master'
      - 'dev'
    paths:
      - 'README.md'
      - 'docs/**'
      - 'src/Docstrings.jl'
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - uses: julia-actions/cache@v2
      - name: Build and deploy
        run: >
          DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24'
          julia --color=yes docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: docs/build
